class OTAError:
    ERROR_CRC_FAIL = 0x01
    ERROR_FLASH_SECTOR_ERASE_FAIL = 0x02
    ERROR_FLASH_BLANK_CHECK_FAIL =  0x03
    ERROR_FLASH_LOCK_FAIL   = 0x04
    ERROR_FLASH_UNLOCK_FAIL = 0x05
    ERROR_FLASH_WRITE_FAIL  = 0x06
    ERROR_FLASH_READ_FAIL   = 0x07
    ERROR_FLASH_READ_PROTECT_FAIL  = 0x08
    ERROR_FLASH_WRITE_PROTECT_FAIL  = 0x09
